### ISSUE TITLE
request: PyPylon binaries?

### ISSUE THREAD

**Issue by ZacDiggum** [mabl/PyPylon#13]
Hi,
I need to operate a Basler Ace acA3800-14um with my Python 3.5 software and I'm having a hard time figuring out the dependencies for PyPylon. Could you provide the module precompiled for Win 7 64 (Pylon SDK 5.0.5 installed)? That would be a big help for me. If not, could you give install instructions?

**Comment by mabl** [comment]
Hi @ZacDiggum,

I'm hesitant to push binaries to PyPI, since this is really early alpha software and is only developed by me and specific to what I need.

However, building for 3.5 under Windows shouldn't be too hard:
1. Download Microsoft Visual Studio Community Edition 2015 (huge Download, but that's the crap you get when running Windows...)
2. Install the Basler Pylon SDK including the Developer options
3. Open up the "Developer Command Propmt for VS2015" (you possible need to match your CPU architecture & Python 32vs64bit, I recommend going 64bit the whole way everywhere)
4. Change into the source repository and do a `python setup.py install`

If this works, let me know or even do a pull request by yourself to add the howto. :-)

**Comment by ZacDiggum** [comment]
I've got it working! :-)
I think the minimal dependencies are Pylon SDK and [Microsoft Build Tools 2015](https://www.microsoft.com/en-us/download/details.aspx?id=48159).
I just played around a little with the camera but can confirm that grabbing images and setting resolution and exposure time are working.
Regarding the accessible parameters: the descriptions printed out with examples/list_cameras.py is very helpful. Could you give me a hint where to find accepted values (float,str,min,max etc.) in the Pylon SDK docs? Or maybe add them to the descriptions in the future?
Great package! Thanks a lot!

**Comment by mabl** [comment]
Great! I plan to add the valid values and data types soonish. They are currently not exposed via the wrapper. However, you do get an error if you are out of range.
